#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    s=sum(arr)
    l2=[]
    for i in arr:
        temp=s-i
        l2.append(temp)
    print(min(l2),max(l2))

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
